### ISSUE TITLE
dev-fs/gocryptfs: add mount* symlinks

### ISSUE THREAD

**Issue by gerion0** [zpuskas/sinustrom-gentoo-overlay#1]
Thank you for packaging gocryptfs. Can you add two additional symlinks within the install process:
```
lrwxrwxrwx 1 root root  18  8. Feb 15:28 /usr/sbin/mount.fuse.gocryptfs -> /usr/bin/gocryptfs
lrwxrwxrwx 1 root root  18  8. Feb 15:41 /usr/sbin/mount.gocryptfs -> /usr/bin/gocryptfs
```
This matches the file layout of sshfs and enables to specify gocryptfs mount points in `/etc/fstab` (and systemd mount units), like so:

```
/path/to/encrypted/dir /path/to/plain/dir fuse.gocryptfs ...,passfile=/path/to/passfile 0 0
```

**Comment by zpuskas** [comment]
Thanks for the report. TIL as per `man mount` EXTERNAL HELPERS section. Can do. :)
