### ISSUE TITLE
media-sound/gonic: fix ExecStart path

### ISSUE THREAD

**Issue by sparkhom** [zpuskas/sinustrom-gentoo-overlay#2]
Thanks for packaging gonic! Unfortunately, I had to make some changes to the unit file after installing it. Turns out that the ExecStart path in the upstream systemd unit file was referencing `/usr/local/bin/gonic`, but it was actually installed to `/usr/sbin/gonic`.

**Comment by zpuskas** [comment]
Good catch, thanks for the report! I'll fix this along with the new 0.16.4 release bump.
